### ISSUE TITLE
404 when visiting site

### ISSUE THREAD

**Issue by Cinderhaze** [spotbugs/eclipse#1]
While trying to navigate to https://spotbugs.github.io/eclipse/, I get a 404.  I'm trying to download the appropriate plugins for offline use without using the marketplace, and I saw some chatter about the 3.1.0 plugin being broken, and wanted to download the previous, working version.

**Comment by iloveeclipse** [comment]
Tbis is **update** site, not a home page or whatever. There is no index.html.

**Comment by Cinderhaze** [comment]
I thought I would be able to find each of the different release versions of the plugin jars, but browsing though the gh-pages area, I only see the most current one.  Is there no way to access the historical plugins without going directly though the eclipse marketplace?

**Comment by demonfiddler** [comment]
I am unable to install SpotBugs into Eclipse Oxygen.1A. Using Help > Install New Software I can see SpotBugs category and IU listed but when I select it and hit Next, Finish, I get the following error:

An error occurred while collecting items to be installed
session context was:(profile=C__eclipse-4.7.0-x86_64_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.github.spotbugs.plugin.eclipse,3.1.0.r201710241414-11c9895
No repository found containing: org.eclipse.update.feature,com.github.spotbugs.plugin.eclipse,3.1.0.r201710241414-11c9895
