### ISSUE TITLE
Eclipse plugin doesn't find known null value

### ISSUE THREAD

**Issue by koma0277** [spotbugs/eclipse#2]
I have update our build process from Findbugs 3.0.1 to Spotbugs 3.1.1. At the same time we updated Eclipse from 4.6.2 with Findbugs plugin to Eclipse 4.6.3 with the Spotbugs plugin.
Spotbugs with ANT is working like expected. But the Eclipse plugin doesn't recognize an issue that we found during our ANT checks.

Spotbugs meesage with ANT:
****.java:1132, NP_LOAD_OF_KNOWN_NULL_VALUE, Priorität: Normal

Source code see screenshot.
![spotbugs](https://user-images.githubusercontent.com/35556790/35098939-5ab28c16-fc56-11e7-8c24-df7026f1d71b.png)

I would expect that the Spotbugs plugin finds the same issues like the ANT integration. I have tried various configurations (analysis effort, minimum rank to report) without succes.

**Comment by iloveeclipse** [comment]
- Is this a regression compared to 3.0.1 plugin?
- Please make sure you have proper project settings (report all warnings, rank 20, prio low etc)
- if this problem remains, please provide a self contained eclipse project where the problem can be reproduced

**Comment by iloveeclipse** [comment]
BTW, I've just realized the issue is opened on a wrong project. Please open this (with extra info added) on https://github.com/spotbugs/spotbugs/issues.

This one is for deployment only.
